#!/bin/bash

pip install -r binder/requirements.txt
python -m bash_kernel.install

wget https://github.com/mrirecon/bart/archive/v0.7.00.tar.gz
tar xzf v0.7.00.tar.gz
mv bart-0.7.00 bart
cd bart
PARALLEL=1 make
