#!/bin/bash
pip install bash_kernel numpy matplotlib h5py scipy

python -m bash_kernel.install

git clone https://github.com/mrirecon/bart/
cd bart
PARALLEL=1 make
cd ..

git clone https://github.com/mrirecon/view/
cd view
PARALLEL=1 TOOLBOX_PATH=../bart make cfl2png




